language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"
# Scripts to be run such as tests
before_script:
  - echo "no tests"
script:
  - docker build -t reverseproxy ./udagram-reverseproxy
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend

  # Tagging
  - docker tag reverseproxy tranquocnha180800/reverseproxy:v2
  - docker tag udagram-api-feed tranquocnha180800/udagram-api-feed:v7
  - docker tag udagram-api-user tranquocnha180800/udagram-api-user:v4
  - docker tag udagram-frontend tranquocnha180800/udagram-frontend:v10

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push tranquocnha180800/reverseproxy:v4
  - docker push tranquocnha180800/udagram-api-feed:v7
  - docker push tranquocnha180800/udagram-api-user:v4
  - docker push tranquocnha180800/udagram-frontend:v10